### ISSUE TITLE
Show multiple mutations in the PCA plot

### ISSUE THREAD

**Issue by gurdeep330** [raimondilab/precogx#92]
@raimondifranc said 
"another very helpful update would be giving the possibility to visualize multiple input sequence/mutations on the PCA panel"

**Comment by maticmarin** [comment]
@gurdeep330  I'm testing this with 15 different sequences and it does run but PCA panel isn't visible. Can you see it or is it just me https://precogxb.bioinfolab.sns.it/output/XWLM8

**Comment by gurdeep330** [comment]
Thanks for reporting this @maticmarin. This is arising because precogx internally assigns '_' to the sequence names before processing. I see that this led to some internal conflict and hence the error.

I have opened another issue to address this. Will update you ASAP. A quick way to avoid this, for now, is to replace _ in the sequence name with something else like, say ':'
You can quickly do this by typing: ```cat input.fasta | tr '_' ':' > newInput.fasta ``` in your terminal. I did this for you already and here is the [output](https://precogxb.bioinfolab.sns.it/output/Y2DP2).

Looking at the output, another question arose (@maticmarin @raimondifranc). Currently, if you input point mutations, it will display all the mutations (of the same protein) in the PCA plot eg: [output](https://precogxb.bioinfolab.sns.it/output/TASPA). In other words, you must specify the "/" with the Uniprot ID or in the sequence name (if provided input in the FASTA format). I imagined that to be @raimondifranc idea. Or do you guys prefer to have all the inputs (even from different proteins) to be displayed in the PCA plot?

**Comment by gurdeep330** [comment]
refer #95
