### ISSUE TITLE
Plotly is down (PCA and Attention map not working)

### ISSUE THREAD

**Issue by gurdeep330** [raimondilab/precogx#96]
@raimondifranc @nataliarosa9 

Plotly (via CDN) has been down for a while (right click -> inspect and you should see the plotly error):
https://precogx.bioinfolab.sns.it/output/AF5JJ

![image](https://github.com/raimondilab/precogx/assets/43615259/b476a142-72b0-4d1d-be33-62c18ccb3465)

**Comment by gurdeep330** [comment]
@nataliarosa9 @raimondifranc 

I have now downloaded and locally saved the latest Plotly version:
`static/js/plotly-plotly.js-da2cd8c/dist/plotly.min.js`

And also updated the [base.html](https://github.com/raimondilab/precogx/blob/b9da485feb6526729348d9729224a7613e4c925b/templates/base.html#L103) to import the local version rather than calling it via CDN.

It works fine on my local system. Could one of you also check on your end? If all is good then you may update the web app too.

Cheers!

**Comment by nataliarosa9** [comment]
@gurdeep330 @raimondifranc 

On the result page, I've updated the import of the local version. 
It works perfectly on both my local and online versions.

Thanks for the help!
Best!

**Comment by raimondifranc** [comment]
Hi Gurdeep,

sorry for the late reply, thx a lot for pointing out the issue!
Hope you are doing great!

Hugs to everyone there!
Best,
Francesco
